[player]
speed = 1200.0
jump_speed = 1600.0
size = 180.0

[arena]
width = 2600.0
height = 1100.0
player_spacing = 900.0
wall_thickness = 10.0
ball_start_x = -900.0
ball_start_y = 300.0

[gravity]
player = 3500.0
ball = 1800.0

[ball]
size = 90.0

[wall]
width = 10.0

[net]
width = 20.0
height = 200.0

[ui]
font_size = 33.0
scoreboard_margin = 5.0

[audio]
volume = 0.2

[controls]
player1_move_left = "KeyA"
player1_move_right = "KeyS"
player1_jump = "KeyW"
player2_move_left = "KeyN"
player2_move_right = "KeyI"
player2_jump = "KeyU"

[window]
title = "Bearing Ball"
mode = "BorderlessFullscreen"
width = 1920
height = 1080 
